const trivia = [
{id:1,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Who was the villain of & "The Lion King"?',correct_answer:'Scar'},
{id:2,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What is the standard frame rate for animation?',correct_answer:'24 FPS'},
{id:3,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'What was the first Disney movie to use CGI?',correct_answer:'The Black Cauldron'},
{id:4,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What is the cartoon character, Andy Capp, known as in Germany?',correct_answer:'Willi Wakker'},
{id:5,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'What is lost in Hawaiian and is also the name of a little girl in a 2002 film which features a alien named "Stitch"?',correct_answer:'Lilo'},
{id:6,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What is the name of the Alligator that The Simpsons "killed" in the episode "Kill The Alligator and Run"?',correct_answer:'Captain Jack'},
{id:7,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What is the name of Ruby Rose\'s weapon from RWBY?',correct_answer:'Crescent Rose'},
{id:8,category:'Cartoons & Animations',type:'boolean',difficulty:'easy',question:'In the "Shrek" film franchise, Donkey is played by Eddie Murphy.',correct_answer:'True'},
{id:9,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What is Scooby-Doo\'s real name?',correct_answer:'Scoobert'},
{id:10,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'Who played Stan\'s dog in the South Park episode "Big Gay Al\'s Big Gay Boat Ride"?',correct_answer:'George Clooney'},
{id:11,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Which \'Family Guy\' character got his own spin-off show in 2009?',correct_answer:'Cleveland Brown'},
{id:12,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'What town was "Springfield" from "The Simpsons" originally named after?',correct_answer:'Springfield, Oregon'},
{id:13,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Butters Stotch, Pip Pirrup, and Wendy Testaburger are all characters in which long running animated TV series?',correct_answer:'South Park'},
{id:14,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Who is the only voice actor to have a speaking part in all of the Disney Pixar feature films? ',correct_answer:'John Ratzenberger'},
{id:15,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'When did the last episode of "Futurama" air?',correct_answer:'September 4, 2013'},
{id:16,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What year was the Disney film "A Goofy Movie" released?',correct_answer:'1995'},
{id:17,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Who voices for Ruby in the animated series RWBY?',correct_answer:'Lindsay Jones'},
{id:18,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What is the standard frame rate for animation?',correct_answer:'24 FPS'},
{id:19,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What Cartoon Network show aired its first episode on November 4th, 2013?',correct_answer:'Steven Universe'},
{id:20,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'In the web-comic Homestuck, what is the name of the game the 4 kids play?',correct_answer:'Sburb'},
{id:21,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'In the 1993 Disney animated series "Bonkers", what is the name of Bonker\'s second partner?',correct_answer:'Miranda Wright'},
{id:22,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Who created the Cartoon Network series "Adventure Time"?',correct_answer:'Pendleton Ward'},
{id:23,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'In the animated series RWBY, what is the name of the weapon used by Weiss Schnee?',correct_answer:'Myrtenaster'},
{id:24,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'In "The Amazing World of Gumball", who is the principal of Elmore Junior High?',correct_answer:'Principal Brown'},
{id:25,category:'Cartoons & Animations',type:'boolean',difficulty:'medium',question:'Nickelodeon rejected the pilot to Adventure Time.',correct_answer:'True'},
{id:26,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'Who created "RWBY"?',correct_answer:'Monty Oum'},
{id:27,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Who was the villain of "The Lion King"?',correct_answer:'Scar'},
{id:28,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'In "Gravity Falls", the character Bill Cipher remarks that "the universe is what?"',correct_answer:'A hologram '},
{id:29,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'In "Rick and Morty", from which dimension do Rick and Morty originate from?',correct_answer:'C-137'},
{id:30,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'In "Gravity Falls", what does Quentin Trembley do when he is driven out from the White House?',correct_answer:'Eat a salamander and jump out the window.'},
{id:31,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What is Dipper\'s real name from "Gravity Falls"?',correct_answer:'Mason Pines'},
{id:32,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'In the "Star Wars" universe, what species is Grand Admiral Thrawn?',correct_answer:'Chiss'},
{id:33,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What was the number on Gerald\'s shirt in "Hey Arnold!"?',correct_answer:'33'},
{id:34,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'In the 1969 Cartoon show "Dastardly and Muttley in Their Flying Machines", which were NOT one of the lyrics in the opening theme?',correct_answer:'Stab him'},
{id:35,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'What was the name of Jonny\'s pet dog in The Adventures of Jonny Quest?',correct_answer:'Bandit'},
{id:36,category:'Cartoons & Animations',type:'boolean',difficulty:'medium',question:'Nutcracker Suite was one of the musical pieces featured in Disney\'s 1940\'s film Fantasia.',correct_answer:'True'},
{id:37,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'Who voiced Finn in Adventure Time?',correct_answer:'Jeremy Shada'},
{id:38,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'Nickelodeon is owned by what parent company?',correct_answer:'Viacom'},
{id:39,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'Townsend Coleman provided the voice for which turtle in the original 1987 series of "Teenage Mutant Ninja Turtles"?',correct_answer:'Michelangelo'},
{id:40,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'In the show "Fat Albert and the Cosby Kids", what is the name of the characters\' fictional gang?',correct_answer:'The Junkyard Gang'},
{id:41,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What ability does Princess Sofia the First have from her amulet that allows her to breathe underwater?',correct_answer:'Mermaid Transformation'},
{id:42,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'In The Simpsons, which war did Seymour Skinner serve in the USA Army as a Green Beret?',correct_answer:'Vietnam War'},
{id:43,category:'Cartoons & Animations',type:'multiple',difficulty:'hard',question:'What was Maggie Simpson\'s first canonical word, not including the Tracey Ullman shorts?',correct_answer:'Daddy.'},
{id:44,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'What animated internet character is known to answer emails with his boxing gloves?',correct_answer:'Strong Bad'},
{id:45,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'Which singer provided the voice of Metroid\'s Mother Brain in the animated series "Captain N: The Game Master"?',correct_answer:'Levi Stubbs'},
{id:46,category:'Cartoons & Animations',type:'boolean',difficulty:'easy',question:'In the "Shrek" film franchise, Donkey is played by Eddie Murphy.',correct_answer:'True'},
{id:47,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'In "Avatar: The Last Airbender", which element does Aang begin to learn after being defrosted?',correct_answer:'Water'},
{id:48,category:'Cartoons & Animations',type:'boolean',difficulty:'medium',question:'Blue Danube was one of the musical pieces featured in Disney\'s 1940\'s film Fantasia.',correct_answer:'False'},
{id:49,category:'Cartoons & Animations',type:'multiple',difficulty:'easy',question:'Butters Stotch, Pip Pirrup, and Wendy Testaburger are all characters in which long running animated TV series?',correct_answer:'South Park'},
{id:50,category:'Cartoons & Animations',type:'multiple',difficulty:'medium',question:'Which city did Anger berate for ruining pizza in "Inside Out"?',correct_answer:'San Francisco'},
{id:51,category:'Music', type:'multiple',difficulty:'medium',question:'The song "Twin Size Mattress" was written by which band?',correct_answer:'The Front Bottoms'},
{id:52,category:'Music', type:'multiple',difficulty:'medium',question:'Which singer was featured in Swedish producer Avicii\'s song "Wake Me Up"?',correct_answer:'Aloe Blacc'},
{id:53,category:'Music', type:'boolean',difficulty:'medium',question:'Scottish producer Calvin Harris is from the town of Dumfries, Scotland.',correct_answer:'True'},
{id:54,category:'Music', type:'multiple',difficulty:'medium',question:'What year was Red Hot Chill Pepper\'s album "Californication" released?',correct_answer:'1999'},
{id:55,category:'Music', type:'multiple',difficulty:'easy',question:'What album did The Lumineers release in 2016?',correct_answer:'Cleopatra'},
{id:56,category:'Music', type:'multiple',difficulty:'easy',question:'"The Singing Cowboy" Gene Autry is credited with the first recording for all but which classic Christmas jingle?',correct_answer:'White Christmas'},
{id:57,category:'Music', type:'multiple',difficulty:'medium',question:'"Make You Feel My Love" was originally written and performed by which singer-songwriter?',correct_answer:'Bob Dylan'},
{id:58,category:'Music', type:'multiple',difficulty:'medium',question:'In what year was Tchaikovsky\'s 1812 Overture composed?',correct_answer:'1880'},
{id:101,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'Which river flows through the Scottish city of Glasgow?',correct_answer:'Clyde'},
{id:102,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'In the video-game franchise Kingdom Hearts, the main protagonist, carries a weapon with what shape?',correct_answer:'Key'},
{id:103,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'Which best selling toy of 1983 caused hysteria, resulting in riots breaking out in stores?',correct_answer:'Cabbage Patch Kids'},
{id:104,category:'General Knowledge',type:'boolean',difficulty:'medium',question:'"Typewriter" is the longest word that can be typed using only the first row on a QWERTY keyboard.',correct_answer:'True'},
{id:105,category:'General Knowledge',type:'boolean',difficulty:'easy',question:'French is an official language in Canada.',correct_answer:'True'},
{id:106,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What does the \'S\' stand for in the abbreviation SIM, as in SIM card? ',correct_answer:'Subscriber'},
{id:107,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What word represents the letter \'T\' in the NATO phonetic alphabet?',correct_answer:'Tango'},
{id:108,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What alcoholic drink is made from molasses?',correct_answer:'Rum'},
{id:109,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What geometric shape is generally used for stop signs?',correct_answer:'Octagon'},
{id:110,category:'General Knowledge',type:'multiple',difficulty:'hard',question:'The words "bungalow" and "shampoo" originate from the languages of which country?',correct_answer:'India'},
{id:111,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'What is the name of the very first video uploaded to YouTube?',correct_answer:'Me at the zoo'},
{id:112,category:'General Knowledge',type:'boolean',difficulty:'medium',question:'The bikini is named after the "Bikini Atoll", an island where the United States conducted tests on atomic bombs.',correct_answer:'True'},
{id:113,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'Red Vines is a brand of what type of candy?',correct_answer:'Licorice'},
{id:114,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What is on display in the Madame Tussaud\'s museum in London?',correct_answer:'Wax sculptures'},
{id:115,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'What is the name given to Indian food cooked over charcoal in a clay oven?',correct_answer:'Tandoori'},
{id:116,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'What is the Swedish word for "window"?',correct_answer:'F&ouml;nster'},
{id:117,category:'General Knowledge',type:'multiple',difficulty:'hard',question:'What is the romanized Chinese word for "airplane"?',correct_answer:'Feiji'},
{id:118,category:'General Knowledge',type:'boolean',difficulty:'easy',question:'The Sun rises from the North.',correct_answer:'False'},
{id:119,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'The term "scientist" was coined in which year?',correct_answer:'1833'},
{id:120,category:'General Knowledge',type:'boolean',difficulty:'medium',question:'Kissing someone for one minute burns about 2 calories.',correct_answer:'True'},
{id:121,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'What is the last letter of the Greek alphabet?',correct_answer:'Omega'},
{id:122,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'Who is depicted on the US hundred dollar bill?',correct_answer:'Benjamin Franklin'},
{id:123,category:'General Knowledge',type:'boolean',difficulty:'easy',question:'The Lego Group was founded in 1932.',correct_answer:'True'},
{id:124,category:'General Knowledge',type:'boolean',difficulty:'easy',question:'One of Donald Trump\'s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.',correct_answer:'True'},
{id:125,category:'General Knowledge',type:'multiple',difficulty:'hard',question:'How many calories are in a 355 ml can of Pepsi Cola?',correct_answer:'150'},
{id:126,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'The New York Times slogan is, &ldquo;All the News That&rsquo;s Fit to&hellip;&rdquo;',correct_answer:'Print'},
{id:127,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'In what year was McDonald\'s founded?',correct_answer:'1955'},
{id:128,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What do the letters of the fast food chain KFC stand for?',correct_answer:'Kentucky Fried Chicken'},
{id:129,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'What is the Portuguese word for "Brazil"?',correct_answer:'Brasil'},
{id:130,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'Where does water from Poland Spring water bottles come from?',correct_answer:'Maine, United States'},
{id:131,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'When did the website "Facebook" launch?',correct_answer:'2004'},
{id:132,category:'General Knowledge',type:'multiple',difficulty:'hard',question:'If someone said "you are olid", what would they mean?',correct_answer:'You smell extremely unpleasant.'},
{id:133,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'Whose greyscale face is on the kappa emoticon on Twitch?',correct_answer:'Josh DeSeno'},
{id:134,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'In which fast food chain can you order a Jamocha Shake?',correct_answer:'Arby\'s'},
{id:135,category:'General Knowledge',type:'multiple',difficulty:'hard',question:'Nephelococcygia is the practice of doing what?',correct_answer:'Finding shapes in clouds'},
{id:136,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'According to the nursery rhyme, what fruit did Little Jack Horner pull out of his Christmas pie?',correct_answer:'Plum'},
{id:137,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'In ancient Greece, if your job were a "hippeus" which of these would you own?',correct_answer:'Horse'},
{id:138,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'A statue of Charles Darwin sits in what London museum?',correct_answer:'Natural History Museum'},
{id:139,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'The Flag of the European Union has how many stars on it?',correct_answer:'12'},
{id:140,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'When one is "envious", they are said to be what color?',correct_answer:'Green'},
{id:141,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What is the closest planet to our solar system\'s sun?',correct_answer:'Mercury'},
{id:142,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'What is the full title of the Prime Minister of the UK?',correct_answer:'First Lord of the Treasury'},
{id:143,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'Foie gras is a French delicacy typically made from what part of a duck or goose?',correct_answer:'Liver'},
{id:144,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'Who is the youngest person to recieve a Nobel Prize?',correct_answer:'Malala Yousafzai'},
{id:145,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'The drug cartel run by Pablo Escobar originated in which South American city?',correct_answer:'Medell&iacute;n'},
{id:146,category:'General Knowledge',type:'boolean',difficulty:'medium',question:'Coca-Cola\'s original colour was green.',correct_answer:'False'},
{id:147,category:'General Knowledge',type:'multiple',difficulty:'easy',question:'What is on display in the Madame Tussaud\'s museum in London?',correct_answer:'Wax sculptures'},
{id:148,category:'General Knowledge',type:'multiple',difficulty:'hard',question:'What is the romanized Chinese word for "airplane"?',correct_answer:'Feiji'},
{id:149,category:'General Knowledge',type:'boolean',difficulty:'medium',question:'Fast food restaurant chains Carl\'s Jr. and Hardee\'s are owned by the same company.',correct_answer:'True'},
{id:150,category:'General Knowledge',type:'multiple',difficulty:'medium',question:'What is the Portuguese word for "Brazil"?',correct_answer:'Brasil'}
]

const cat = [
    { id:1 , category:'General Knowledge'},
    { id:2 , category:'Music'},
    { id:3 , category:'Cartoons & Animations'},
]

module.exports = { trivia, cat };
